"""add_payment_infrastructure_and_user_extensions

Revision ID: cb8a1baee725
Revises: 4642b31090bc
Create Date: 2025-10-01 23:51:09.450201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb8a1baee725'
down_revision: Union[str, Sequence[str], None] = '4642b31090bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_status'), 'payment_records', ['status'], unique=False)
    op.create_index('ix_payment_records_status_created', 'payment_records', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_records_stripe_invoice_id'), 'payment_records', ['stripe_invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_records_stripe_payment_intent_id'), 'payment_records', ['stripe_payment_intent_id'], unique=True)
    op.create_index('ix_payment_records_user_created', 'payment_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_records_user_id'), 'payment_records', ['user_id'], unique=False)
    op.create_index('ix_payment_records_user_status', 'payment_records', ['user_id', 'status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ACADEMIC', name='subscriptiontier'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', 'PAST_DUE', 'TRIALING', 'UNPAID', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index('ix_subscriptions_tier_status', 'subscriptions', ['tier', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('request_duration_ms', sa.Integer(), nullable=True),
    sa.Column('billing_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ACADEMIC', name='subscriptiontier'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_billing_period'), 'usage_records', ['billing_period'], unique=False)
    op.create_index(op.f('ix_usage_records_endpoint'), 'usage_records', ['endpoint'], unique=False)
    op.create_index('ix_usage_records_endpoint_timestamp', 'usage_records', ['endpoint', 'timestamp'], unique=False)
    op.create_index(op.f('ix_usage_records_subscription_tier'), 'usage_records', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_usage_records_timestamp'), 'usage_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index('ix_usage_records_user_period', 'usage_records', ['user_id', 'billing_period'], unique=False)
    op.create_index('ix_usage_records_user_timestamp', 'usage_records', ['user_id', 'timestamp'], unique=False)
    op.add_column('users', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ACADEMIC', name='subscriptiontier'), nullable=False, server_default='FREE'))
    op.add_column('users', sa.Column('subscription_status', sa.Enum('ACTIVE', 'CANCELED', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', 'PAST_DUE', 'TRIALING', 'UNPAID', name='subscriptionstatus'), nullable=False, server_default='ACTIVE'))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_index('ix_usage_records_user_timestamp', table_name='usage_records')
    op.drop_index('ix_usage_records_user_period', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_timestamp'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_subscription_tier'), table_name='usage_records')
    op.drop_index('ix_usage_records_endpoint_timestamp', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_endpoint'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_billing_period'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_subscriptions_user_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_tier_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_payment_records_user_status', table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_user_id'), table_name='payment_records')
    op.drop_index('ix_payment_records_user_created', table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_stripe_payment_intent_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_stripe_invoice_id'), table_name='payment_records')
    op.drop_index('ix_payment_records_status_created', table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_status'), table_name='payment_records')
    op.drop_table('payment_records')
    # ### end Alembic commands ###
