"""add_refund_and_dispute_tables

Revision ID: ebaa477edc3e
Revises: c7562c0a8dd5
Create Date: 2025-10-02 00:39:24.663769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebaa477edc3e'
down_revision: Union[str, Sequence[str], None] = 'c7562c0a8dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_record_id', sa.Integer(), nullable=True),
    sa.Column('stripe_dispute_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_charge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('WARNING_NEEDS_RESPONSE', 'WARNING_UNDER_REVIEW', 'WARNING_CLOSED', 'NEEDS_RESPONSE', 'UNDER_REVIEW', 'CHARGE_REFUNDED', 'WON', 'LOST', name='disputestatus'), nullable=False),
    sa.Column('reason', sa.Enum('DUPLICATE', 'FRAUDULENT', 'SUBSCRIPTION_CANCELED', 'PRODUCT_UNACCEPTABLE', 'PRODUCT_NOT_RECEIVED', 'UNRECOGNIZED', 'CREDIT_NOT_PROCESSED', 'GENERAL', 'INCORRECT_ACCOUNT_DETAILS', 'INSUFFICIENT_FUNDS', 'BANK_CANNOT_PROCESS', 'DEBIT_NOT_AUTHORIZED', 'CUSTOMER_INITIATED', name='disputereason'), nullable=False),
    sa.Column('evidence_due_by', sa.DateTime(), nullable=True),
    sa.Column('evidence_submitted', sa.Boolean(), nullable=False),
    sa.Column('evidence_details', sa.JSON(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspension_lifted_at', sa.DateTime(), nullable=True),
    sa.Column('dispute_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_record_id'], ['payment_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispute_records_charge_id', 'dispute_records', ['stripe_charge_id'], unique=False)
    op.create_index('ix_dispute_records_evidence_due', 'dispute_records', ['evidence_due_by'], unique=False)
    op.create_index(op.f('ix_dispute_records_payment_record_id'), 'dispute_records', ['payment_record_id'], unique=False)
    op.create_index(op.f('ix_dispute_records_reason'), 'dispute_records', ['reason'], unique=False)
    op.create_index(op.f('ix_dispute_records_status'), 'dispute_records', ['status'], unique=False)
    op.create_index('ix_dispute_records_status_created', 'dispute_records', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_dispute_records_stripe_charge_id'), 'dispute_records', ['stripe_charge_id'], unique=False)
    op.create_index(op.f('ix_dispute_records_stripe_dispute_id'), 'dispute_records', ['stripe_dispute_id'], unique=True)
    op.create_index(op.f('ix_dispute_records_stripe_payment_intent_id'), 'dispute_records', ['stripe_payment_intent_id'], unique=False)
    op.create_index('ix_dispute_records_user_created', 'dispute_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_dispute_records_user_id'), 'dispute_records', ['user_id'], unique=False)
    op.create_index('ix_dispute_records_user_status', 'dispute_records', ['user_id', 'status'], unique=False)
    op.create_table('refund_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_record_id', sa.Integer(), nullable=True),
    sa.Column('stripe_refund_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_charge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'REQUIRES_ACTION', name='refundstatus'), nullable=False),
    sa.Column('reason', sa.Enum('CUSTOMER_REQUEST', 'DUPLICATE', 'FRAUDULENT', 'SUBSCRIPTION_CANCELED', 'ADMIN_ADJUSTMENT', 'DISPUTE', name='refundreason'), nullable=False),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_adjusted', sa.Boolean(), nullable=False),
    sa.Column('subscription_adjustment_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refund_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_record_id'], ['payment_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refund_records_payment_intent', 'refund_records', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_refund_records_payment_record_id'), 'refund_records', ['payment_record_id'], unique=False)
    op.create_index(op.f('ix_refund_records_reason'), 'refund_records', ['reason'], unique=False)
    op.create_index(op.f('ix_refund_records_status'), 'refund_records', ['status'], unique=False)
    op.create_index('ix_refund_records_status_created', 'refund_records', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_refund_records_stripe_charge_id'), 'refund_records', ['stripe_charge_id'], unique=False)
    op.create_index(op.f('ix_refund_records_stripe_payment_intent_id'), 'refund_records', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_refund_records_stripe_refund_id'), 'refund_records', ['stripe_refund_id'], unique=True)
    op.create_index('ix_refund_records_user_created', 'refund_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_refund_records_user_id'), 'refund_records', ['user_id'], unique=False)
    op.create_index('ix_refund_records_user_status', 'refund_records', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refund_records_user_status', table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_user_id'), table_name='refund_records')
    op.drop_index('ix_refund_records_user_created', table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_stripe_refund_id'), table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_stripe_payment_intent_id'), table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_stripe_charge_id'), table_name='refund_records')
    op.drop_index('ix_refund_records_status_created', table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_status'), table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_reason'), table_name='refund_records')
    op.drop_index(op.f('ix_refund_records_payment_record_id'), table_name='refund_records')
    op.drop_index('ix_refund_records_payment_intent', table_name='refund_records')
    op.drop_table('refund_records')
    op.drop_index('ix_dispute_records_user_status', table_name='dispute_records')
    op.drop_index(op.f('ix_dispute_records_user_id'), table_name='dispute_records')
    op.drop_index('ix_dispute_records_user_created', table_name='dispute_records')
    op.drop_index(op.f('ix_dispute_records_stripe_payment_intent_id'), table_name='dispute_records')
    op.drop_index(op.f('ix_dispute_records_stripe_dispute_id'), table_name='dispute_records')
    op.drop_index(op.f('ix_dispute_records_stripe_charge_id'), table_name='dispute_records')
    op.drop_index('ix_dispute_records_status_created', table_name='dispute_records')
    op.drop_index(op.f('ix_dispute_records_status'), table_name='dispute_records')
    op.drop_index(op.f('ix_dispute_records_reason'), table_name='dispute_records')
    op.drop_index(op.f('ix_dispute_records_payment_record_id'), table_name='dispute_records')
    op.drop_index('ix_dispute_records_evidence_due', table_name='dispute_records')
    op.drop_index('ix_dispute_records_charge_id', table_name='dispute_records')
    op.drop_table('dispute_records')
    # ### end Alembic commands ###
